version: '3.8'
volumes:
  datos:
networks:
  database:
  web:
  fila:
services:
  db:
    image:  postgres:9.6.22
    ports:
      - 5432:5432
    volumes:
      - datos:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks: 
      - database
  frontend:
    image: nginx:1.21.0
    volumes: 
      # site
      - ./web:/usr/share/nginx/html
      # proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks: 
      - web
    depends_on: 
      - app
  app: 
    # image: python:3.6
    build: 
      context: ./app
      # dockerfile: Dockerfile-qa
    volumes:
      - ./app:/app
    working_dir: /app
    # probar primero asi y va a dar un error
    # command: ./app.sh
    # solución al error anterior agrego bash
    command: bash ./app.sh
    # ports:
    #   - 3000:3000
    
    networks: 
      - database
      - web
      - fila
    depends_on:
      - db
    environment: 
      - DB_NAME=email_sender
  queue:
    image: redis:6.2.5-alpine
    networks:
      - fila
  worker:
    build: 
      context: ./worker
    volumes: 
      - ./worker:/worker
    working_dir: /worker
    command: worker.py

    networks:
      - fila
    depends_on:
      - queue