version: '3.8'
services:
  db:
    image:  postgres:9.6.22
    ports:
      - 5439:5432
    volumes:
      # - ~/data/pgserver-prod-data:/var/lib/postgresql/data
      - ./data/pgdata:/var/lib/postgresql/data
      # - datos:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
  frontend:
    image: nginx:1.21.0
    volumes: 
      # site
      - ./web:/usr/share/nginx/html
      # Proxy reverso
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  
  app: 
    image: : python:3.13
    volumes:
      - ./app:/app
    working_dir: /app
    command: ./app.sh
    # ports:
    #   - 3000:3000
    
    
volumes: 
  pgdata:

    