---
version: "2"
services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=password
      - DB_DATABASE=bookstackapp
 
    volumes:
      - /home/jcvaldes/dockers/volumes/bookstack:/config
      - /home/jcvaldes/dockers/volumes/uploads:/var/www/bookstack/public/uploads
      - /home/jcvaldes/dockers/volumes/storage-uploads:/var/www/bookstack/public/storage
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: ghcr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=password
      - TZ=America/Argentina/Buenos_Aires
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=password
    volumes:
      - /home/jcvaldes/dockers/volumes/bookstack/db:/config
    restart: unless-stopped