FROM debian
LABEL maintainer="Juan Carlos Valdés <idevkingos@gmail.com>"

# argumento voy a poder pasar en el momento de creacion del build de la imagen
# recibe por defecto pero se puede pasar en el momento de creación
ARG S3_BUCKET=files

#variable de ambiente
ENV S3_BUCKET=${S3_BUCKET}

